#!/usr/bin/env python3
"""
Conditional Subspace Extraction for FPS Conditioning Analysis.

This script extracts and analyzes the conditional subspaces generated by
FPS adapters without running full inference. It computes orthonormal bases
for different FPS conditions and saves them for geometric analysis.

Usage:
    python inference/analyze_conditional_subspace.py \
        --config fps_TOML/wan_SC_TARGET_14B_FPS_SHAPE_BLUR.toml \
        --checkpoint outputs/checkpoint/step_10000 \
        --fps_values 12 24 60 120 240 \
        --output_dir output/subspace_analysis
"""

import torch
import os
import sys
import logging
import argparse
import pickle
import json
from datetime import datetime
from tqdm import tqdm
import numpy as np

# Add project root to path
sys.path.insert(0, '/root/workspace/sc-diffusion-pipe')

from models.wan.wan import WanPipeline
from models.wan.model import compute_tau_rel
from utils.common import DTYPE_MAP
import toml
import deepspeed


def setup_logging():
    """Setup logging configuration."""
    logging.basicConfig(
        level=logging.INFO,
        format="[%(asctime)s] %(levelname)s: %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S"
    )


def setup_environment(port='29501'):
    """Initialize DeepSpeed distributed environment."""
    if not deepspeed.comm.is_initialized():
        os.environ.setdefault('MASTER_ADDR', 'localhost')
        os.environ.setdefault('MASTER_PORT', port)
        os.environ.setdefault('RANK', '0')
        os.environ.setdefault('WORLD_SIZE', '1')
        os.environ.setdefault('LOCAL_RANK', '0')
        deepspeed.init_distributed()
    logging.info(f"DeepSpeed environment initialized on port {port}")


def load_pipeline_from_toml(toml_path):
    """
    Load WanPipeline using TOML configuration.

    Args:
        toml_path: Path to TOML configuration file

    Returns:
        (pipeline, config) tuple
    """
    logging.info(f"Loading TOML configuration: {toml_path}")

    # Load TOML config
    with open(toml_path) as f:
        config = json.loads(json.dumps(toml.load(f)))

    # Convert dtype strings to torch.dtype
    model_dtype_str = config['model']['dtype']
    config['model']['dtype'] = DTYPE_MAP[model_dtype_str]
    if transformer_dtype := config['model'].get('transformer_dtype', None):
        config['model']['transformer_dtype'] = DTYPE_MAP.get(transformer_dtype, transformer_dtype)

    logging.info(f"Model type: {config['model']['type']}")
    logging.info(f"Model dtype: {model_dtype_str} -> {config['model']['dtype']}")

    # Initialize pipeline
    pipeline = WanPipeline(config)

    logging.info("Loading transformer model...")
    pipeline.load_diffusion_model()

    # Move to device and set eval mode
    device = "cuda" if torch.cuda.is_available() else "cpu"
    logging.info(f"Moving model to device: {device}")

    pipeline.transformer.to(device)
    pipeline.transformer.eval()

    logging.info("Pipeline loaded successfully")
    return pipeline, config


def load_checkpoint(pipeline, checkpoint_path):
    """
    Load FPS checkpoint weights.

    Args:
        pipeline: WanPipeline instance
        checkpoint_path: Path to checkpoint directory/file
    """
    import safetensors
    from pathlib import Path

    logging.info(f"Loading checkpoint: {checkpoint_path}")

    checkpoint_dir = Path(checkpoint_path)
    if checkpoint_dir.is_dir():
        safetensors_files = list(checkpoint_dir.glob('*.safetensors'))
        if not safetensors_files:
            raise FileNotFoundError(f"No .safetensors files in {checkpoint_dir}")
        checkpoint_file = safetensors_files[0]
    else:
        checkpoint_file = checkpoint_dir

    # Load checkpoint
    checkpoint = safetensors.torch.load_file(str(checkpoint_file))

    # Filter FPS parameters only
    fps_checkpoint = {k: v for k, v in checkpoint.items()
                     if 'fps_conditioning' in k or 'fps_adapter' in k}

    logging.info(f"Found {len(fps_checkpoint)} FPS parameters in checkpoint")

    # Load into model
    missing_keys, unexpected_keys = pipeline.transformer.load_state_dict(
        fps_checkpoint, strict=False
    )

    logging.info(f"Loaded {len(fps_checkpoint)} FPS parameters")
    if len(missing_keys) > 0:
        logging.info(f"Missing keys (expected for base model params): {len(missing_keys)}")
    if len(unexpected_keys) > 0:
        logging.warning(f"Unexpected keys: {unexpected_keys}")

    logging.info("Checkpoint loaded successfully")


def get_fps_adapters(pipeline):
    """
    Extract FPS adapter modules from transformer blocks.

    Args:
        pipeline: WanPipeline instance

    Returns:
        List of dicts with adapter information
    """
    fps_adapters = []

    for block_idx, block in enumerate(pipeline.transformer.blocks):
        if hasattr(block, 'fps_adapter') and block.fps_adapter is not None:
            adapter = block.fps_adapter
            fps_adapters.append({
                'block_idx': block_idx,
                'adapter': adapter,
                'dim': adapter.dim,
                'num_heads': adapter.num_heads,
                'head_dim': adapter.head_dim,
                'num_tokens': adapter.num_tokens,
                'rank': adapter.rank,
                'fps_conditioning_dim': adapter.fps_conditioning_dim
            })

    logging.info(f"Found {len(fps_adapters)} FPS-adapted blocks:")
    for info in fps_adapters:
        logging.info(f"  Block {info['block_idx']}: "
                    f"dim={info['dim']}, heads={info['num_heads']}, "
                    f"tokens={info['num_tokens']}, rank={info['rank']}")

    return fps_adapters


def compute_fps_embeddings(pipeline, fps_values, device='cuda'):
    """
    Compute FPS conditioning embeddings for different conditions.

    Args:
        pipeline: WanPipeline instance
        fps_values: List of FPS values (scalar or list for multi-condition)
        device: Device to use

    Returns:
        Dict mapping fps_str -> embedding tensor [1, embed_dim]
    """
    logging.info(f"Computing FPS embeddings for {len(fps_values)} conditions")

    fps_embeddings = {}

    # Access FPS conditioning MLP through InitialLayer
    initial_layer = pipeline.to_layers()[0]
    fps_conditioning_mlp = initial_layer.fps_conditioning

    # Get FPS transform parameters
    fps_tau_transform = initial_layer.fps_tau_transform
    fps_tau_scale = initial_layer.fps_tau_scale
    fps_reference_fps = initial_layer.fps_reference_fps

    logging.info(f"FPS transform settings:")
    logging.info(f"  Transform: {fps_tau_transform}")
    logging.info(f"  Scale: {fps_tau_scale}")
    logging.info(f"  Reference FPS: {fps_reference_fps}")

    for fps in tqdm(fps_values, desc="Computing embeddings"):
        # Handle single vs multi-condition
        if isinstance(fps, list):
            fps_tensor = torch.tensor([fps], dtype=torch.float32, device=device)
            fps_str = '_'.join(f"{v:.3f}" for v in fps)
        else:
            fps_tensor = torch.tensor([fps], dtype=torch.float32, device=device)
            fps_str = str(fps)

        # Compute tau_rel transformation
        with torch.no_grad():
            tau_rel = compute_tau_rel(
                fps_tensor,
                reference_fps=fps_reference_fps,
                transform=fps_tau_transform,
                scale=fps_tau_scale
            )

            # Handle shape for single vs multi-condition
            if tau_rel.ndim == 1:
                tau_rel = tau_rel.unsqueeze(-1)

            # Convert to model dtype (fix dtype mismatch)
            model_dtype = next(fps_conditioning_mlp.parameters()).dtype
            tau_rel = tau_rel.to(model_dtype)

            # Pass through FPS conditioning MLP
            fps_embedding = fps_conditioning_mlp(tau_rel)

        fps_embeddings[fps_str] = fps_embedding

        logging.debug(f"  FPS {fps_str}: embedding shape={fps_embedding.shape}, "
                     f"mean={fps_embedding.mean().item():.6f}, "
                     f"std={fps_embedding.std().item():.6f}")

    logging.info(f"Computed {len(fps_embeddings)} FPS embeddings")
    return fps_embeddings


def compute_effective_rank(singular_values, threshold=0.01):
    """
    Compute effective rank based on singular value threshold.

    Args:
        singular_values: Tensor of singular values (sorted descending)
        threshold: Relative threshold (fraction of largest SV)

    Returns:
        Effective rank (int)
    """
    normalized_sv = singular_values / singular_values[0]
    return (normalized_sv > threshold).sum().item()


def generate_conditional_subspace(fps_adapter, fps_embedding, device='cuda'):
    """
    Generate value tensor and orthonormal basis for a condition.

    This is the core of the analysis: we extract the subspace spanned by
    the FPS adapter's value vectors, which constrains all possible outputs
    of the FPS attention mechanism.

    Args:
        fps_adapter: FPSCrossAttentionAdapter module
        fps_embedding: [1, embed_dim] FPS conditioning tensor
        device: Device for computation

    Returns:
        Dict with subspace information including:
            - v_fps: Value tensor [num_tokens, num_heads, head_dim]
            - v_matrix: Flattened matrix [num_tokens*num_heads, head_dim]
            - basis: Orthonormal basis vectors (U from SVD)
            - singular_values: Singular values from SVD
            - effective_rank: Effective dimensionality
            - full_rank: Full rank (min dimension)
    """
    with torch.no_grad():
        # 1) LoRA projection for V: fps_embedding -> low-rank -> full-rank
        v_down = fps_adapter.v_fps_down(fps_embedding)  # [1, rank]
        v_up = fps_adapter.v_fps_up(v_down)             # [1, num_tokens * dim]

        # 2) Apply LoRA scaling
        v_proj = v_up * fps_adapter.lora_scale

        # 3) Reshape to attention format
        num_tokens = fps_adapter.num_tokens
        num_heads = fps_adapter.num_heads
        head_dim = fps_adapter.head_dim

        v_fps = v_proj.view(1, num_tokens, num_heads, head_dim).squeeze(0)
        # Shape: [num_tokens, num_heads, head_dim]

        # 4) Flatten to matrix for SVD
        # Each row is one "value vector" in the attention mechanism
        v_matrix = v_fps.reshape(-1, head_dim)  # [num_tokens * num_heads, head_dim]

        # 5) Compute SVD: v_matrix = U @ diag(S) @ V^T
        # For v_matrix with shape [160, 128]:
        #   - U: [160, 128] - left singular vectors (span row space, i.e., token-head space)
        #   - S: [128] - singular values
        #   - Vh: [128, 128] - right singular vectors (span column space, i.e., head_dim space)
        # We want Vh (right singular vectors) because they form a basis in head_dim space,
        # which is the space where the backbone also operates.
        # Convert to float32 for SVD (BFloat16 not supported on CUDA)
        v_matrix_fp32 = v_matrix.float()
        U, S, Vh = torch.linalg.svd(v_matrix_fp32, full_matrices=False)
        # Convert back to original dtype
        v_matrix = v_matrix_fp32.to(v_matrix.dtype)

        # 6) Compute effective rank
        eff_rank = compute_effective_rank(S, threshold=0.01)

        # 7) Return everything to CPU for storage
        # NOTE: Vh has shape [head_dim, head_dim], rows are basis vectors
        # We transpose to get columns as basis vectors: [head_dim, head_dim]
        return {
            'v_fps': v_fps.cpu(),
            'v_matrix': v_matrix.cpu(),
            'basis': Vh.T.cpu(),                 # Orthonormal basis in head_dim space [head_dim, head_dim]
            'singular_values': S.cpu(),          # For dimensionality analysis
            'effective_rank': eff_rank,
            'full_rank': len(S),
            'num_tokens': num_tokens,
            'num_heads': num_heads,
            'head_dim': head_dim
        }


def extract_all_subspaces(pipeline, fps_values, output_dir, device='cuda'):
    """
    Extract conditional subspaces for all FPS values and blocks.

    This is the main extraction loop that generates all subspace data.

    Args:
        pipeline: Loaded WanPipeline
        fps_values: List of FPS conditions to analyze
        output_dir: Where to save subspace data
        device: Device for computation

    Returns:
        Nested dict: subspace_data[fps_str][block_idx] -> subspace info
    """
    logging.info("="*80)
    logging.info("STARTING CONDITIONAL SUBSPACE EXTRACTION")
    logging.info("="*80)

    os.makedirs(output_dir, exist_ok=True)

    # Step 1: Extract FPS adapters
    fps_adapters = get_fps_adapters(pipeline)
    if len(fps_adapters) == 0:
        raise ValueError("No FPS adapters found in model! Check that checkpoint has FPS parameters.")

    # Step 2: Compute FPS embeddings for all conditions
    fps_embeddings = compute_fps_embeddings(pipeline, fps_values, device)

    # Step 3: Extract subspaces for each (condition, block) pair
    logging.info("\nExtracting conditional subspaces...")
    subspace_data = {}

    for fps in tqdm(fps_values, desc="Processing FPS conditions"):
        # Get string key for this condition
        if isinstance(fps, list):
            fps_str = '_'.join(f"{v:.3f}" for v in fps)
        else:
            fps_str = str(fps)

        fps_embedding = fps_embeddings[fps_str]
        subspace_data[fps_str] = []

        # Extract subspace for each adapted block
        for adapter_info in tqdm(fps_adapters,
                                desc=f"  FPS={fps_str[:20]}",
                                leave=False):
            subspace_info = generate_conditional_subspace(
                adapter_info['adapter'],
                fps_embedding,
                device
            )

            # Add block metadata
            subspace_info['block_idx'] = adapter_info['block_idx']
            subspace_info['adapter_dim'] = adapter_info['dim']
            subspace_info['adapter_rank'] = adapter_info['rank']

            subspace_data[fps_str].append(subspace_info)

    # Step 4: Save to disk
    output_file = os.path.join(output_dir, 'subspace_data.pkl')
    logging.info(f"\nSaving subspace data to {output_file}")

    with open(output_file, 'wb') as f:
        pickle.dump(subspace_data, f)

    # Step 5: Save metadata
    metadata = {
        'fps_values': fps_values,
        'num_conditions': len(fps_values),
        'num_blocks': len(fps_adapters),
        'block_indices': [info['block_idx'] for info in fps_adapters],
        'extraction_time': datetime.now().isoformat(),
        'config_file': pipeline.config.get('model', {}).get('ckpt_path', 'unknown')
    }

    metadata_file = os.path.join(output_dir, 'metadata.json')
    with open(metadata_file, 'w') as f:
        json.dump(metadata, f, indent=2)

    logging.info(f"Saved metadata to {metadata_file}")

    # Step 6: Print summary
    logging.info("\n" + "="*80)
    logging.info("EXTRACTION COMPLETE")
    logging.info("="*80)
    logging.info(f"Conditions analyzed: {len(fps_values)}")
    logging.info(f"Blocks analyzed: {len(fps_adapters)}")
    logging.info(f"Total subspaces: {len(fps_values) * len(fps_adapters)}")
    logging.info(f"Output directory: {output_dir}")

    # Print sample statistics
    logging.info("\nSample statistics (first condition, first block):")
    first_fps_str = list(subspace_data.keys())[0]
    first_subspace = subspace_data[first_fps_str][0]
    logging.info(f"  FPS condition: {first_fps_str}")
    logging.info(f"  Block: {first_subspace['block_idx']}")
    logging.info(f"  Effective rank: {first_subspace['effective_rank']}/{first_subspace['full_rank']}")
    logging.info(f"  Rank ratio: {first_subspace['effective_rank']/first_subspace['full_rank']:.3f}")
    logging.info(f"  Max singular value: {first_subspace['singular_values'][0]:.6f}")
    logging.info(f"  Min singular value: {first_subspace['singular_values'][-1]:.6f}")

    return subspace_data


def parse_fps_values(fps_values_flat, num_conditions):
    """
    Parse flat fps_values list into groups based on num_conditions.

    Args:
        fps_values_flat: Flat list of floats from command line
        num_conditions: Number of conditions (1 for single, 2+ for multi)

    Returns:
        List of fps_values (scalars for single, lists for multi)
    """
    if num_conditions == 1:
        return fps_values_flat
    else:
        if len(fps_values_flat) % num_conditions != 0:
            raise ValueError(
                f"fps_values length ({len(fps_values_flat)}) must be divisible by "
                f"num_conditions ({num_conditions})"
            )

        grouped = []
        for i in range(0, len(fps_values_flat), num_conditions):
            group = fps_values_flat[i:i+num_conditions]
            grouped.append(group)

        return grouped


def main():
    parser = argparse.ArgumentParser(
        description='Extract conditional subspaces from FPS adapters',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Single-condition model
  python inference/analyze_conditional_subspace.py \\
      --config fps_TOML/wan_SC_TARGET_14B_FPS_SHAPE_BLUR.toml \\
      --checkpoint outputs/checkpoint/step_10000 \\
      --fps_values 12 24 60 120 240 \\
      --output_dir output/subspace_analysis

  # Multi-condition model (2 conditions)
  python inference/analyze_conditional_subspace.py \\
      --config shutter_bokeh_TOML/wan_SC_TARGET_14B_2SHAPES_SHUTTER_BOKEH.toml \\
      --checkpoint outputs/multi_checkpoint/step_5000 \\
      --fps_values 0.5 0.02  1.0 0.05  0.125 0.1 \\
      --output_dir output/multi_subspace
        """
    )

    parser.add_argument('--config', required=True,
                       help='Path to TOML configuration file')
    parser.add_argument('--checkpoint', required=True,
                       help='Path to checkpoint directory/file')
    parser.add_argument('--fps_values', nargs='+', type=float, required=True,
                       help='FPS values to analyze (flat list, auto-grouped for multi-condition)')
    parser.add_argument('--output_dir', default='output/subspace_analysis',
                       help='Output directory for subspace data')
    parser.add_argument('--port', default='29502',
                       help='DeepSpeed port')
    parser.add_argument('--device', default='cuda',
                       help='Device to use (cuda/cpu)')

    args = parser.parse_args()

    try:
        # Setup
        setup_logging()
        setup_environment(args.port)

        # Load pipeline
        pipeline, config = load_pipeline_from_toml(args.config)

        # Load checkpoint
        load_checkpoint(pipeline, args.checkpoint)

        # Detect number of conditions
        fps_tau_transform = config.get('model', {}).get('fps_tau_transform', 'log1p')
        if isinstance(fps_tau_transform, list):
            num_conditions = len(fps_tau_transform)
        else:
            num_conditions = 1

        logging.info(f"Detected {num_conditions}-condition model")

        # Parse FPS values
        fps_values = parse_fps_values(args.fps_values, num_conditions)
        logging.info(f"FPS conditions to analyze: {fps_values}")

        # Extract subspaces
        subspace_data = extract_all_subspaces(
            pipeline,
            fps_values,
            args.output_dir,
            device=args.device
        )

        logging.info("\n✅ Subspace extraction completed successfully!")
        logging.info(f"Next step: Run geometric analysis on {args.output_dir}/subspace_data.pkl")

        return 0

    except Exception as e:
        logging.error(f"❌ Subspace extraction failed: {e}")
        import traceback
        traceback.print_exc()
        return 1


if __name__ == "__main__":
    exit(main())
